spring.application.name=backend

# --- Connexion a la base PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/merombe
spring.datasource.username=postgres
spring.datasource.password=merombe2026
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
# none = Hibernate ne touche pas aux tables, c'est ton script SQL qui commande
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# la connexion est rendue des la fin du traitement, pas a la fin de l'affichage
spring.jpa.open-in-view=false

# --- Serveur ---
server.port=8080